const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--disable-renderer-backgrounding','--disable-background-timer-throttling']});try{
 const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.goto('http://127.0.0.1:8765/_teacher_ui_preview.html');await page.frameLocator('iframe').locator('.attention-row').first().waitFor();const frame=await page.locator('iframe').elementHandle().then(e=>e.contentFrame());await frame.waitForFunction(()=>!!window.TeachingUI,{},{polling:100});
 await frame.evaluate(()=>{
  students=[{num:1,name:'하늘'},{num:2,name:'다온'}];examResults=[];counselRecords=[];counselRequests=[];peskWritingsAll=[];writings=[];
  window.mockDocs={};window.failSave=false;_db={};_fsDoc=(base,...parts)=>typeof base==='string'?base+'/'+parts.join('/'):parts.join('/');_fsCollection=_fsDoc;
  _fsGetDoc=async ref=>({exists:()=>Object.hasOwn(mockDocs,ref),data:()=>structuredClone(mockDocs[ref])});
  _fsGetDocs=async ref=>({docs:Object.entries(mockDocs).filter(([k])=>k.startsWith(ref+'/')&&!k.slice(ref.length+1).includes('/')).map(([k,v])=>({id:k.split('/').at(-1),data:()=>structuredClone(v)}))});
  _fsRunTxn=async(_,fn)=>{const writes=[];const value=await fn({get:_fsGetDoc,set:(k,v)=>writes.push([k,v])});if(failSave)throw Error('unavailable');for(const [k,v]of writes)mockDocs[k]=structuredClone(v);return value;};
  goPage('exam');openExamModal();
 });
 await frame.locator('#exam-name').fill('수학 연습');await frame.locator('#exam-total').fill('2');await frame.locator('#exam-score-1').fill('40');await frame.locator('#exam-wrong-2').fill('0');
 // Preserve entered work while changing the selected roster.
 await frame.locator('.exam-stu-check[data-num="2"]').uncheck();assert.equal(await frame.locator('#exam-score-1').inputValue(),'40');await frame.locator('.exam-stu-check[data-num="2"]').check();assert.equal(await frame.locator('#exam-wrong-2').inputValue(),'0');
 await frame.evaluate(()=>submitExam());await frame.locator('#teach-question-editor').waitFor();
 assert.match(await frame.locator('#exam-content').innerText(),/40점/);assert.doesNotMatch(await frame.locator('#exam-content').innerText(),/완벽한 성적/);assert.equal(await frame.evaluate(()=>examResults[0].avgScore),70);
 await frame.locator('#teach-question-editor summary').click();await frame.locator('[data-question="1"] [data-q="text"]').fill('1 더하기 1은?');await frame.locator('[data-question="1"] [data-q="answer"]').fill('2');await frame.locator('[data-question="1"] [data-q="skill"]').fill('덧셈');await frame.locator('[data-question="1"] [data-q="confirmed"]').check();await frame.locator('[data-teach="questions"]').click();await frame.waitForFunction(()=>examResults[0].questions.some(q=>q.confirmed));
 await frame.evaluate(()=>{const ex=examResults[0];ex.results[0].wrongKnown=true;ex.results[0].wrongs=[1];mockDocs['classrooms/'+TESK_ROOM+'/data/tesk-exams'].value=structuredClone(examResults);renderExamDetail(ex.id);callTeachAI=async()=>JSON.stringify({items:[{sourceNo:1,question:'2 더하기 1은?',answer:'3',explanation:'둘에 하나를 더하면 셋입니다.'}]});});
 await frame.locator('[data-teach="twins"]').click();await frame.locator('#teach-twin-reviewed').waitFor();assert.equal(await frame.evaluate(()=>examResults[0].twinReviewed),false);await frame.locator('#teach-twin-reviewed').check();await frame.locator('[data-teach="review"]').click();await frame.waitForFunction(()=>examResults[0].twinReviewed);
 fs.mkdirSync('output/teaching',{recursive:true});await page.screenshot({path:'output/teaching/exam.png'});
 await frame.evaluate(()=>{goPage('counsel');openCounselModal();});await frame.locator('#teach-counsel-voice').fill('쉬는 시간에 같이 놀고 싶어요');await frame.locator('#counsel-text-input').fill('쉬는 시간에 혼자 서 있는 모습을 보았다.');await frame.locator('#teach-counsel-mood').fill('불안');await frame.locator('#teach-counsel-state').selectOption('followup');await frame.locator('#counsel-plan').fill('원하는 놀이를 따로 물어보기');await frame.locator('#teach-counsel-review').fill('2026-10-01');
 await frame.evaluate(()=>failSave=true);await frame.evaluate(()=>submitCounsel());assert.equal(await frame.evaluate(()=>counselRecords.length),0);assert.equal(await frame.locator('#teach-counsel-voice').inputValue(),'쉬는 시간에 같이 놀고 싶어요');await frame.evaluate(()=>failSave=false);await frame.evaluate(()=>submitCounsel());console.log('counsel saved state',await frame.evaluate(()=>({records:counselRecords,toast:document.querySelector('#toast')?.textContent,detail:counselDetailId})));await frame.locator('#teach-counsel-ai').waitFor({state:'attached'});assert.equal(await frame.evaluate(()=>counselRecords[0].risk),null);
 await frame.evaluate(()=>{callTeachAI=async()=>JSON.stringify({quote:'같이 놀고 싶어요',todo:['원하는 놀이 확인하기'],opening:'이야기해 줘서 고마워.',questions:['어떤 놀이를 하고 싶니?'],closing:'선생님이 무엇을 도와줄까?',avoid:'혼자 있는 이유를 캐묻기'});});await frame.locator('[data-teach="prep"]').click();await frame.locator('#teach-counsel-ai').getByText('이야기를 듣는 발문',{exact:true}).waitFor();
 await frame.locator('[data-teach="edit"]').click();await frame.locator('#teach-counsel-outcome').fill('함께 놀고 싶은 놀이를 구체적으로 이야기했다.');await frame.locator('#teach-counsel-state').selectOption('closed');await frame.evaluate(()=>submitCounsel());assert.equal(await frame.evaluate(()=>counselRecords[0].history.length),1);assert.equal(await frame.evaluate(()=>counselRecords[0].state),'closed');await page.screenshot({path:'output/teaching/counsel.png'});
 await frame.evaluate(async()=>{const w={id:'draft-one',studentNum:1,studentName:'하늘',title:'쉬는 시간',content:'친구가 기다려 주었다. 함께 공놀이를 했다.',feedback:'친구의 행동이 잘 드러나요.',revision:1,submittedAt:new Date().toISOString()};mockDocs['classrooms/'+TESK_ROOM+'/data/pesk-writings/items/'+w.id]=structuredClone(w);peskWritingsAll=[w];const next=await writingStore().update(w.id,c=>({...c,content:c.content+' 고마운 마음이 들었다.'}));applyPeskWritingEntry(next);goPage('writing');openPeskWritingFeedback(w.id);callTeachAI=async()=>JSON.stringify({quote:'기다려 주었다',strength:'친구의 행동이 드러나요.',nextStep:'친구에게 하고 싶은 말을 한 문장 보태세요.',question:'친구에게 어떤 말을 하고 싶니?',feedback:'친구의 행동이 잘 보여요. 하고 싶은 말을 보태볼까요?'});});
 await frame.locator('#ai-writing-fb-btn').click();await frame.locator('#teach-writing-evidence blockquote').waitFor({state:'attached'});assert.equal(await frame.locator('.teach-original mark').innerText(),'기다려 주었다');
 // '고쳐쓰기 지도' 상자는 숨기고(교사 요청), 숨긴 목표 칸의 AI 값은 학생에게 보내지 않는다
 assert.equal(await frame.locator('.teach-writing-coach').isHidden(),true);assert.equal(await frame.locator('#wr-proof').isVisible(),true);
 await frame.evaluate(()=>submitPeskFeedback('draft-one'));assert.equal(await frame.evaluate(()=>peskWritingsAll[0].needsRevisionReview),false);assert.equal(await frame.evaluate(()=>peskWritingsAll[0].learningGoal),'');await page.screenshot({path:'output/teaching/writing.png'});
 // A changed server draft must not receive feedback for old text.
 await frame.evaluate(()=>mockDocs['classrooms/'+TESK_ROOM+'/data/pesk-writings/items/draft-one'].content='서버에서 바뀐 글');await frame.locator('#pesk-fb-text').fill('오래된 초안의 피드백');await frame.evaluate(()=>submitPeskFeedback('draft-one'));assert.notEqual(await frame.evaluate(()=>mockDocs['classrooms/'+TESK_ROOM+'/data/pesk-writings/items/draft-one'].feedback),'오래된 초안의 피드백');
 await page.setViewportSize({width:390,height:844});for(const name of ['writing','exam','counsel']){await frame.evaluate(n=>goPage(n),name);assert.ok(await frame.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' mobile overflow');}await page.screenshot({path:'output/teaching/mobile.png'});assert.deepEqual(errors,[]);console.log('PASS teaching workflows: exam input/confirmed questions/twins, counsel save failure/history/mood, writing evidence/revision/stale feedback, mobile.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

